### ISSUE TITLE
 プロジェクト環境をセットアップする

### ISSUE THREAD

**Issue by tetsuyanh** [digitech-ymg/renofa-parking-web#1]
## ゴール
- [x] 開発者がREADME.mdで環境構築の手順や各種実行コマンドを知ることができる
- [x] 開発者が起動コマンドでローカル動作を確認できる

## 概要
チームで技術選定の合意を取って、その環境をセットアップする。

原田はこれが一番詳しくてメジャーなのでこれでいきたいがどうでしょう？
- Nextjs（Reactフレームワーク）
- TailWindCSS（CSS）
- TypeScript（型導入）
- Prettier（コードの整形）
- ESLint（構文チェック）
- husky（Git操作自動制約）

**Comment by nishidayoshikatsu** [comment]
## 構成決定
- Nextjs（Reactフレームワーク）
- Chakra UI（CSS）
- TypeScript（型導入）
- Prettier（コードの整形）
- ESLint（構文チェック）
- husky（Git操作自動制約）
