### ISSUE TITLE
ホスティングして公開する

### ISSUE THREAD

**Issue by tetsuyanh** [digitech-ymg/renofa-parking-web#2]
## ゴール
- [ ] 開発者が最新コードの成果物をホスティングサービスにデプロイできる
- [ ] URLを知っている人がWebサイトを閲覧することができる

## 概要
Webへのアクセスも当面少ないので、しばらくは無料でマネージドなホスティングにデプロイする。
レノファ公認になるまでは、ホスティングサービスのドメインURLでOKです。

私は最近、Firebase Hostingを使ってますが、他を推す方が要れば要相談で。
対抗はNetlify？Vercel？

**Comment by nishidayoshikatsu** [comment]
@tetsuyanh 
公式のexampleを見る限り、cloud functionsを利用するみたいですが、無料プランだと確かできないですよね？
https://github.com/vercel/next.js/tree/canary/examples/with-firebase-hosting

**Comment by nishidayoshikatsu** [comment]
静的ホスティングならできますね。すみません
https://code-log.hatenablog.com/entry/2020/02/23/200541

https://github.com/digitech-ymg/renofa-parking-web/issues/2#issuecomment-961583797

**Comment by nishidayoshikatsu** [comment]
@tetsuyanh 
静的ホスティング微妙だなあと作業しててなったのですが、Netlifyで取り組んでみても大丈夫ですかね？

https://github.com/digitech-ymg/renofa-parking-web/discussions/11

**Comment by nishidayoshikatsu** [comment]
> ~静的ホスティング微妙だなあと作業しててなったのですが、Netlifyで取り組んでみても大丈夫ですかね？~
> 
> ~#11~

Firebase Hostingでデプロイします（）

**Comment by nishidayoshikatsu** [comment]
うーん、`firebase init`できない問題...
Github Organizationのfirebase cli権限がapproveされてること、firebase cliのアカウントが自分のものであることは確認したし、あとはなんだろ
firebase側の権限必要なのかな？

`Error: HTTP Error: 403, Policy update access denied.`

issueにはorganizationが承認してればいいって書いてるしなあ

https://github.com/FirebaseExtended/action-hosting-deploy/issues/40
https://github.com/firebase/firebase-tools/issues/3143

**Comment by nishidayoshikatsu** [comment]
CICDの設定は後回しにして、とりあえずホスティング完了
https://renofa-parking.web.app/

**Comment by nishidayoshikatsu** [comment]
.firebaseはgitignoreに含めた方が良いという話

https://uga-box.hatenablog.com/entry/2021/07/28/000000

> このファイルはFirebaseHostingの新機能の一部であり、前回のデプロイ以降に変更されたファイルのみをアップロードすることで、ホスティングデプロイメントの時間のサイズを最小限に抑えます。これはCLIバージョン4.2.0の新機能であり、GitHubで読むことができる
