### ISSUE TITLE
CI/CDの設定

### ISSUE THREAD

**Issue by tetsuyanh** [digitech-ymg/renofa-parking-web#3]
## ゴール
- [ ] 開発者が任意のブランチをPushした時に、Github上で自動で検証（lint/test/buildなど）が走る
- [x] レビュアーがPR（任意のブランチ→mainブランチ）をマージした時に、自動でホスティングサービスにデプロイされる

## 概要
CI/CDはGithub Actionsで良いか。（選択肢としてはCircle CIなど？）

**Comment by nishidayoshikatsu** [comment]
良さそう
https://zenn.dev/watarukun/articles/8f3e318bacf97cabf879

**Comment by nishidayoshikatsu** [comment]
やっぱりfirebase側の権限不足っぽい

https://stackoverflow.com/questions/63995958/firebase-init-functions-returns-403-caller-does-not-have-permission
