### ISSUE TITLE
初期プロトタイプのデザインカンプを作成する

### ISSUE THREAD

**Issue by tetsuyanh** [digitech-ymg/renofa-parking-web#4]
## ゴール

- [x] スマホ画面サイズの3ページのレイアウトやCSSの詳細を確認できる
  - [x] 開発者がトップページを実装可能な状態になる
  - [x] 開発者が駐車場ページを実装可能な状態になる
  - [x] 開発者がサイト説明ページを実装可能な状態になる
  - [x] URLを知っている人が完成イメージを確認できる
- [x] PC画面サイズの3ページのレイアウトがざっくり確認できる
  - モバイル用途が前提なので大きな違和感や表示崩れがなければ良しとする

## 概要

ラフな下書きしかないので、Webデザインの設計指示書に清書してほしい。。
Figma（AdobeXD？）でどうでしょう？

・トップページ（左）
ヘッダーは仮置きのもので。。
駐車場全ての位置が入った地図は書き起こしが必要か？（最悪、リストで列挙か？）
リンクバナーはレノファ公式サイトのみで。（CSSで簡素なバナー？🦁）  
フッターMO仮置きのもので。。

・駐車場ページ（中）
駐車場名はドロップダウンで、他の駐車場にも切り替えられるように。
予測グラフのレイアウト？見せ方？は検討の余地あるので、一旦スペースだけ空けて保留にすべきか？
（グラフチャートの）
GoogleMapは簡単にエンベッドできる？

・サイト（右）
運営の方に用意してもらった文章をはめるだけで良い。
デジテックの方にあるプロジェクトカード（画像でいい）を置く。

![レノファ山口駐車場情報サイト（仮）](https://user-images.githubusercontent.com/1460298/138559459-f89dbe56-64fa-4cd0-bc80-7272652a8874.jpg)

**Comment by tetsuyanh** [comment]
@watagit 
> ・トップページ（左）
ヘッダーは仮置きのもので。。
駐車場全ての位置が入った地図は書き起こしが必要か？（最悪、リストで列挙か？）

こちらですが、地図全体のイラストなり画像を用意する見込みがないため
リスト形式でもしょうがないと考えてます。

わたぽんさんの方で既に地図表現の手段方法（実装）の目処や見込みなどあれば、それを採用してもらっても構いません。

**Comment by watagit** [comment]
@tetsuyanh 
そうですね、イラストや画像が用意されないのであれば、より簡単な実装にしても良いかなと思いました！
リスト形式というのは、駐車場名をリスト表示するという理解で合っていますか？

イメージ的には（駐車場名は仮）↓
<img src="https://user-images.githubusercontent.com/44804976/140269971-b86e460e-f574-44a8-8d8f-17a056fa1fa2.png" width="300" />

**Comment by tetsuyanh** [comment]
@watagit 
> 駐車場名をリスト表示するという理解で合っていますか？
ですです。これで行きましょうー。
